### ISSUE TITLE
List of bugs/things that came up during demo and some playing around

### ISSUE THREAD

**Issue by kaushik12** [tsdataclinic/scout#126]
- Sort by has `name` and `Name`. Don't know what the difference is. 
- Potential join columns: when you click `View`, the site goes blank and hitting the back button doesn't help either.
- When you click on a thematically similar dataset, it isn't clear that the page reloaded and the clicked dataset is now displayed on the left. I had a user clicking it multiple times and claiming nothing happens unless pointed to the descriptions changing on the left. Perhaps these open in a new tab?
- 311 Service Requests from 2010 to Present still shows the same dataset as a thematically similar one and only a 98% similarity which is weird. 
- View on Open Data button isn't clear given it looks similar in size and color to `Add to collection`. I had a couple of people ask, "so, how do I download this data now". I think we should highlight that a bit more and use "Download" as a keyword maybe instead of "View".
- Since Datasets in under each column in Potential join columns tab populate on the fly, if I move from looking at one column to another, I have to wait for the previous one to finish running before the next one starts populating. 
- Collections: If you don't have an existing collection, you can still click on "Switch collection" which breaks the feature. 
- About page: A color separator between the "Lots of Datasets are lonely" and  "What is Data Clinic" would be nice. Cos the circles kinda looks like it's the Data Clinic logo and right above it. 
- "by Data Clinic" under Scout is super tiny and barely readable. Maybe we think a bit more about how to present that. 
- Twitter medium and Github links perhaps could be Horizontally laid out.
- Adding standard TS Disclaimer/ Terms of use/ privacy policy

**Comment by els2171** [comment]
About page:
- [ ] Section 1 paragraph 1: change "dataset's" to "datasets"
- [ ] Section 1 paragraph 2: change "scot" to "scout"
- [ ] Section 2 title: change "Lot's" to "Lots"
- [ ] Section 2 paragraph 1: change "there is lots of" to "there is a lot of"

**Comment by stuartlynn** [comment]
Closing this ticket as the issues have either been addressed or moved in to their own separate tickets
