### ISSUE TITLE
Task - Rethink the "View on Open Data" button design

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#130]
Button appears to confuse people, might need to think about a redesign.

Feedback from other issue:
> View on Open Data button isn't clear given it looks similar in size and color to Add to collection. I had a couple of people ask, "so, how do I download this data now". I think we should highlight that a bit more and use "Download" as a keyword maybe instead of "View".

Note here that I dont think we should change it's name to Download as I would expect that to be a direct download link. I think "View on Open Data" Or "See more details" or something similar might be better

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
