### ISSUE TITLE
Feature - Move dataset filtering to web worker

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#138]
Currently, on older machines, there is some UI slowdown when filtering the datasets. This could be resolved in two ways. 

1. Increase the debounce on the search so that it will not trigger quite so frequently
2. Move the filtering to a web worker so that it doesn't slow down the UI
3, Generally look for ways to make the filtering faster.

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
