### ISSUE TITLE
Develop an API server for the metadata and suggestions

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#145]
Currently scout uses a client side database ([IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)  via [dexie](https://dexie.org/) )) to store, search and organize the metadata of the open data portals a user is interested in. This has worked well for a single open data portal and scales to a few open data portals but if we want to increase the number of datasets we can index and add more features, we need to move to a backend server. 

We have started building this server using [nest.js](https://nestjs.com/), [graphql](https://graphql.org/) and [typeorm](https://typeorm.io/#/) on this repo: https://github.com/tsdataclinic/ScoutAPI

We could use help with the following 

1) Extending the API to allow the fetching of suggestions, both in join columns and thematic similarities 
2) Running CRON jobs (through the nextjs scheduling system) to pull in new datasets from the data portals and to run the ML scripts for similarity and join able datasets.
3) Stub out a domain model for collected column categories 
4) Stub out an API for collections 
5) Add authentication based on OAuth to the API to support user collections

**Comment by jps327** [comment]
This is done!
