### ISSUE TITLE
Optomize dexie queries and database structure

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#146]
In the current version of [multi city scout](https://github.com/tsdataclinic/scout/tree/mulit-city) we use [dexie](https://dexie.org/) and [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) to store the data about the open data portals in a client side DB.

Many of these queries could be optimized either by using a smarter query or by changing up the database structure. Places to look for wins would be 

1. The search function that allows a user to filter all datasets and do fuzzy text searching 
https://github.com/tsdataclinic/scout/blob/86cab19b25d478ccac4f99fbeef3ecbc38b90ca2/src/hooks/datasets.js#L175-L243

2. The query that looks for datasets with similar columns
https://github.com/tsdataclinic/scout/blob/86cab19b25d478ccac4f99fbeef3ecbc38b90ca2/src/hooks/datasets.js#L43-L60

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
