### ISSUE TITLE
Github code recomendations

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#147]
A feature I would love to add to scout is the ability to hi-light github repos that use a specific dataset. The Socrata id is fairly distinctive and we could use it to search for codebases that use that dataset. 

This would be valuable to a user in identifying 

1. Projects that might indicate how to use the dataset properly 
2. Cleaning scripts to make the datasets more useful
3. Additional documentation about the dataset. 

GIthub supplies an API for searching code on the system : https://docs.github.com/en/free-pro-team@latest/rest/reference/search

The API has two modes and authenticated mode with about 30 requests per minute limit and a unauthenticated mode with 10 requests per minute. 

Given that we should hit up the unauthenticated API from the client size which means each individual user (with a different IP) will be able to query up to 10 datasets per minute. 

An example of an API query to search for the street tree census (https://scout.tsdataclinic.com/dataset/uvpi-gqnh ) in issues would look like this:

https://api.github.com/search/issues?q=uvpi-gqnh

https://github.com/search?q=uvpi-gqnh&type=code

Currently it looks like the github API wont let us search all code. We might want to include the all code link however or find a way of exposing that page as an iframe

- [ ] Explore the github API to get a feel for what is possible / how many datasets we get hits for
- [ ] Add either a hook to get results from the API for a given datasets or a hook to generate an iframe embed of the page 
- [ ] Add a tab to the dataset page alongside the join column and thematically similar tabs called "code" and implement an interface to show the resulting code links

**Comment by jps327** [comment]
Github feature has been added but can do with more expanding in other issues
