### ISSUE TITLE
Implment collections

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#148]
We need to move the logic for implementing collections to the backend server. This means 

- [ ] Defining an entry for the collections types 
- [ ] Building a service for the entries that allows creation, updating, deletion and search. 
- [ ] Build out the graphql endpints to interact with the collections service
- [ ] Integrate with an authentication framework

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
