### ISSUE TITLE
[Design] Make dropdown selection text bigger

### ISSUE THREAD

**Issue by bettyquinn** [tsdataclinic/scout#166]
The text within the dropdown for the selected portal can probably be larger. 

TO do: Betty to determine font size and whether the search bar width should be adjusted

**Comment by jps327** [comment]
@bettyquinn We're doing triage of issues on Scout. Does this issue still need addressing or is it safe to close?

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
