### ISSUE TITLE
[Design] Add hover states to text links

### ISSUE THREAD

**Issue by bettyquinn** [tsdataclinic/scout#167]
When a user hovers over text links, it should change color (Betty to provide hex code)

This affects:

- Pagination
- Dropdowns
- Toggle between Matching Columns and Thematically Similar on detail pages

**Comment by jps327** [comment]
@bettyquinn We're doing triage of issues on Scout. Does this issue still need addressing or is it safe to close?

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
