### ISSUE TITLE
Make selected portal more clear on Details page

### ISSUE THREAD

**Issue by bettyquinn** [tsdataclinic/scout#170]
(Betty to hand off specs) 

Users could forget what portal they have selected if the label is: "Just this portal". The selected portal's name should appear on the details page.

**Comment by jps327** [comment]
@bettyquinn We're doing triage of issues on Scout. Does this issue still need addressing or is it safe to close?

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
