### ISSUE TITLE
User Stories for multi city

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#176]
- [ ] As a researcher who is searching for all the data about 911 calls
 I want to be able to optionally see similar datasets segmented by city 
 so that I can quickly identify which cities potentially have data available

- [ ] As a data scientists who has been sent a collection 
I want to be able to view datasets in the collection by city 
to quickly understand the geographic scope of that collection

- [ ] As a data scientist searching for datasets about budget in their state
I want to be able to optionally filter my search results to include datasets from my states portal , and all cities and orgs that are within my state
to ensure I am finding all relevant datasets.

- [ ] As a researcher who is looking to compare traffic accidents in two different cities
I want to be able to filter search results to only those two cities
to find comparable relevant datasets.

- [ ] As a researcher who is attempting to understand how much open data there is about crime at the city level
I want to filter only by data portals at the city level and have those results grouped by city 
so that I can make a quick assessment of how much each city publishes crime data.

**Comment by stuartlynn** [comment]
Potentially for #2 show locations on a map

**Comment by bettyquinn** [comment]
![Collection - Interactive Map](https://user-images.githubusercontent.com/60236310/110679594-a2738a00-81a5-11eb-87f0-5457a9b38549.png)
![Portal cards - large](https://user-images.githubusercontent.com/60236310/110679597-a30c2080-81a5-11eb-980d-5dd75d8dce75.png)
![Portal cards - small](https://user-images.githubusercontent.com/60236310/110679598-a30c2080-81a5-11eb-9bce-88a4ff5531be.png)

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
