### ISSUE TITLE
Identify 20 columns to use as a starting point for this process.

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#185]
They should have high impact in that they are present in a lot of datasets and have a high significance in NYC. For example, link a lot of data about various health programs

Deliverable s :

A dataframe of columns, the datasets they are present on, their types.

A dataframe of the unique ids present across the entire open data portal that are found in those columns

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
