### ISSUE TITLE
For the 20 trial columns, produce a script that tries to identify groupings of ids and potentially the canonically correct id for each group.

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#186]
We can either do this programmatically or   by finding a secondary column that we can use to identify the groups that exists on one of the member datasets. So for example school names can probably be grouped and identified by BBL or something similar which should be cleaner

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
