### ISSUE TITLE
Identify a database schema to represent the crosswalks.

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#187]
This probably composes of 2 tables 1 to hold the canonical id's and one to hold the mappings from individual unique ids to the canonical ids.

Open question is if this is a mapping between each unique id on a given dataset to the canonical id or from the unique id across the entire data portal to the canonical id.

The later gives us more flexibility for cases where the same id has different contexts or uses in two different datasets but has the same string or integer representation, but increases the database complex and the amount of work that needs to be crowd sourced.

One want to decide this would be to take a look at the results of the exploration of the top 20 id types

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
