### ISSUE TITLE
Flesh out prototype interface for allowing users to give feedback on crosswalks.

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#188]
We have a very quick sketch of what the interface to allow feedback on crosswalks should look like. We need better designs for these and a mocked up version so that we can start user testing it with people. 

Use static files from the data exploration phase to try and build a version of this that explores the various complexities without needing the backend support for now

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
