### ISSUE TITLE
Need to fix the default on home page - keeps going back to New York datasets

### ISSUE THREAD

**Issue by mosymns13** [tsdataclinic/scout#237]
Hello there! I want to bring a potential bug to your attention. 

I have been trying to take a look at other cities (specifically Austin).  Once I click on a dataset to explore and then go "home", I am taken back to NY datasets. This happens each time whether I am using the filters or not. 

The toggle is on for "specific portal." The same thing happens regardless of the browser (Firefox, Safari, and Chrome).

**Comment by jps327** [comment]
Thank you for bringing this to our attention! It looks like we aren't tracking your currently selected portal in the app state once you leave the Explore page. That means that when you go back to the Explore page, after having left it, it resets to New York.

This should be easy to fix and we will prioritize this for next week.

**Comment by mosymns13** [comment]
Oh wow! Thanks for getting to it so quickly. This will be a great help for my work this week 👍🏾
