### ISSUE TITLE
Feature - Method to invalidate the cache on new version

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/scout#39]
Post launch we are going to need a way to invalidate the cache when we push a new feature that changes the data structure.

Perhaps we record the last cache update in the local store. Then when we push a new version that requires a cache invalidation, we include a deploy timestamp that can be checked against the cache update timestamp. If it is newer we invalidate the cache.

**Comment by jps327** [comment]
Closing stale issues as part of task triage and preparing for a new roadmap
